### ISSUE TITLE
Transient data design

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#120]
## Type changes
Transient data can be a mutation on the solution data like:
```rust
pub struct Solution {
    pub data: Vec<SolutionData>,
    pub transient_data: Vec<StateMutation>,
    pub state_mutations: Vec<StateMutation>,
}
```
*Maybe we rename `StateMutation` but it will be the same type for both `state_mutations` and `transient_data`.*
## New ASM
```yaml
Transient:
  stack_in: [pathway, key_0, ...key_N, key_len]
  stack_out:
    elem: slot_word
    len: value_len

TransientLen:
  stack_in: [pathway, key_0, ...key_N, key_len]
  stack_out: [len]

IntentAt:
  stack_in: [pathway]
  stack_out: [set_key_0, set_key_1, set_key_2, set_key_3, intent_key_0, intent_key_1, intent_key_2, intent_key_3]
```
`IntentAt` is needed to confirm the intent at the pathway is the one this intent was expecting it to be.

These probably need better names but we need ops to get information about the transient data that is using this op as a pathway.
```yaml
# Similar to MutKeysLen
ThisTransientLen:
  stack_out: [len]

# Similar to MutKeysContains
ThisTransientContains:
  stack_in: [key_0, key_n, key_len]
  stack_out[bool]
```
## In the VM
Transient data should be stored as:
```rust
Arc<HashMap<SolutionDataIndex, HashMap<Key, Vec<Word>>>>
// or if we want to support key ranges
Arc<HashMap<SolutionDataIndex, BtreeMap<Key, Vec<Word>>>>
```
This way it can be efficiently retrieved from any state read program or constraint program.
