### ISSUE TITLE
Compute Op Design

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#189]
Works like a compute shader.
```mermaid
stateDiagram-v2
    [*] --> a: [Z]
    a --> c: R
    c --> [*]: bool
```
```yaml
Compute:
  stack_in: [amount],
  stack_out: [index],
```
Once this is called the rest of the bytecode runs (potentially) in parallel. Each compute gets a unique index on the stack.
Each compute clones the stack and can write to it. 
Each compute gets it's own memory to write to. Memory is concatenated at the `ComputeEnd` op.
