### ISSUE TITLE
Implement Layered Memory Access

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#261]
Create a memory access system that respects the layered approach, allowing VMs to read from shared memory but only write to their local memory.

- [ ] Implement load memory to check local memory first, then shared memory
- [ ] Modify store memory to only write to local memory
- [ ] Add memory bounds checking for trying to write to shared memory
- [ ] Implement memory allocation tracking for local memory

**Comment by mitchmindtree** [comment]
@freesig I'm doing some thinking on this and after some chats with @supiket I'm wondering if we can take a simpler approach that doesn't involve layering.

## Proposed Approach

In compute shaders, you generally have totally separate buffers for reading (input) and writing (output), and both are indexed totally independently (there's no layering).

Maybe we can do something similar here, where we just have separate `ParentMemory::Load` and `ParentMemory::LoadRange` ops for accessing `parent_memory` (which just error if used in a non-compute context).

Then, in the compute op we always start each "thread" with empty memory, and allow them to build it up as necessary? Then we don't need to track anything fancy about local memory allocation, or change any of the existing `Memory` ops, and we can just directly concatenate all thread `Memory`s to form the output.

```
    ParentMemory:
      description: Operations for reading parent memory from within a compute context.
      group:
        Load:
          opcode: 0x7A
          short: PLOD
          description: Load the value at the given index from parent memory onto the stack.
          panics:
            - Called outside compute context.
            - Index is out of bounds.
          stack_in: [index]
          stack_out: [value]

        LoadRange:
          opcode: 0x7B
          short: PLODR
          description: Load a range of words starting at the index within parent memory.
          panics:
            - Called outside compute context.
            - Index is out of bounds.
            - Index + len is out of bounds.
          stack_in: [index, len]
          stack_out: [values]
```
