### ISSUE TITLE
Design transient data

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#31]
The ability to access decision variables from other intents within the same solution:
```yaml
            TransientDecisionVar:
              opcode: 0x??
              description: |
                Access a decision variable in a different solution data by `Intent Set Address`, `Intent Address`, `instance`, `slot`.

                The Intent must be included in the solution data.
                The instance refers to which instance of the intent to use (when there is more then one of the same intent).
                The instance is 0 indexed and must be in range. 
                So if it's set to `1` there must be two instances of the intent in the solution data.
                The slot must be in range.

                Returns a decision word.
              panics:
                - The slot is out of range.
                - There is no intent in the solution matching the address and instance.
              stack_in: [set_address_w0, set_address_w1, set_address_w2, intent_address_w3, intent_address_w0, intent_address_w1, intent_address_w2, intent_address_w3, instance, slot]
              stack_out: [decision_word]

            TransientDecisionVarRange:
              opcode: 0x??
              description: |
                Access a range of decision variables starting from a specified `Intent Set Address`, `Intent Address`, `instance`, `slot`.

                Returns a list of decision words with length equal to the specified range.
              panics:
                - The range `slot..(slot + range)` is out of range.
                - There is no intent in the solution matching the address and instance.
              stack_in: [set_address_w0, set_address_w1, set_address_w2, intent_address_w3, intent_address_w0, intent_address_w1, intent_address_w2, intent_address_w3, instance, slot, range]
              stack_out:
                elem: decision_word
                len: range

```
