### ISSUE TITLE
eq_range

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#75]
# Eq Range
Compares two ranges within the stack for equality.
Does **not** pop anything off the stack.
Returns `false` if the lens of the range are not equal.
```yaml
EqRange:
  stack_in: [start_a, end_a, start_b, end_b]
  stack_out: [bool]
```
# Eq Range Dec Var
Compares a range of decision variables with a range of words on the stack.
Does **not** pop anything off the stack.
Returns `false` if the lens of the range are not equal.
```yaml
EqRangeDecVar:
  stack_in: [start_dec, end_dec, start_stack, end_stack]
  stack_out: [bool]
```
# Eq Range State
Compares a range of state with a range of words on the stack.
Does **not** pop anything off the stack.
Returns `false` if the lens of the range are not equal.
```yaml
EqRangeState:
  stack_in: [start_state, end_state, delta, start_stack, end_stack]
  stack_out: [bool]
```
# Alternative
We could give only a single `length` like `stack_in: [start_a, start_b, len]` and separately check the lengths are equal.
