### ISSUE TITLE
swap_index

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#76]
Swaps a word at an arbitrary index in the stake with the word on the top of the stack.
`0` is the index of the element at the top of the stack.
```yaml
SwapIndex:
  stack_in: [a, b, c, d, index]
  stack_out: [a, d, c, b]
```
