### ISSUE TITLE
select

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#77]
Pops a condition and two words off the stack. If the condition is `true` then it pushes `a` back onto the stack. If the condition is `false` it pushes `b` back onto the stack.
```yaml
Select:
  stack_in: [a, b, cond]
  stack_out: [a]
```
