### ISSUE TITLE
recover_secp256k1

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#79]
```yaml
RecoverSecp256k1:
  stack_in: [data, data_len, sig_w0, sig_w1, sig_w2, sig_w3, sig_w4, sig_w5, sig_w6, sig_w7, sig_8]
  stack_out: [key_w0, key_w1, key_w2, key_w3, key_w4]
```
The returned key will be `[0, 0, 0, 0, 0]` if the recovery fails.
