### ISSUE TITLE
mut_key_contains

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#80]
Puts a `true` on the stack if the key is contained within the set of currently proposed keys.
```yaml
MutKeysContains:
  stack_in:
    elem: key
    len: key_num_words
  stack_out: [bool]
```
